global:
  ## Альтернатива ограниченным yaml-алиасам Helm'а. Даёт возможность не дублировать одну и ту же конфигурацию много раз.
  #
  # Здесь, в "global._includes", объявляются блоки конфигурации, которые потом можно использовать в любых values-файлах.
  # Пример подтягивания этих блоков конфигурации в репозитории приложения:
  # -----------------------------------------------------------------------------------------------
  # .helm/values.yaml:
  # -----------------------------------------------------------------------------------------------
  # apps-cronjobs:
  #   cronjob-1:
  #     _include: ["apps-cronjobs.defaultCronJob"]
  #     backoffLimit: 1
  # -----------------------------------------------------------------------------------------------
  #
  # В примере выше конфигурация из include-блока "apps-cronjobs.defaultCronJob" развернётся на уровне
  # apps-cronjobs.cronjob-1, а потом поверх развернувшейся конфигурации применится параметр "backoffLimit: 1",
  # при необходимости перезаписав параметр "backoffLimit" из include-блока.
  #
  # Подробнее: https://github.com/flant/helm-charts/tree/master/.helm/charts/flant-lib#flexpandincludesinvalues-function
  _includes:
    apps-default-imagePullSecrets:
      imagePullSecrets: |
        - name: registrysecret
    apps-default-priorityClassName:
      priorityClassName:
        _default: "production-medium"
        production: "production-high"

    ## Конфигурация по умолчанию для приложения в целом.
    apps-stateless-defaultApp:
      enabled: false
      _include:
      - apps-default-imagePullSecrets
      revisionHistoryLimit: 3
      annotations: |
        pod-reloader.deckhouse.io/auto: "true"
      strategy:
        _default: |
          rollingUpdate:
            maxSurge: 20%
            maxUnavailable: 50%
          type: RollingUpdate
        production: |
          rollingUpdate:
            maxSurge: 20%
            maxUnavailable: 25%
          type: RollingUpdate
      podDisruptionBudget:
        enabled: true
        maxUnavailable: "15%"
      horizontalPodAutoscaler:
        enabled:
          _default: false

    ## Конфигурация по умолчанию для приложения в целом.
    apps-stateful-defaultApp:
      _include:
        - apps-default-enabled
        - apps-default-imagePullSecrets
      revisionHistoryLimit: 3
      annotations: |
        pod-reloader.deckhouse.io/auto: "true"
      strategy:
        _default: |
          rollingUpdate:
            maxSurge: 20%
            maxUnavailable: 50%
          type: RollingUpdate
        production: |
          rollingUpdate:
            maxSurge: 20%
            maxUnavailable: 25%
          type: RollingUpdate
      podDisruptionBudget:
        enabled: true
        maxUnavailable: "15%"
      verticalPodAutoscaler:
        enabled: true
        updateMode:
          _default: "Auto"
          production: "Off"
        resourcePolicy: |
          {}
      horizontalPodAutoscaler:
        enabled:
          _default: false
      service:
        enabled: false
        name: "{{ $.CurrentApp.name }}"

    apps-jobs-defaultJob:
      enabled: false
      _include:
      - apps-default-imagePullSecrets
      - apps-default-priorityClassName
      - apps-default-nodeAffinityAndTolerations
      restartPolicy: "Never"

    ## Конфигурация по умолчанию для инит-контейнера приложения.
    apps-initContainer-wait-pgsql:
      wait-pgsql:
        image:
          name: "postgres_client"
        command:
          - /bin/sh
          - -c
          - |
            until psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -p ${DB_PASSWORD}
            --execute=\"SELECT 1;\"; do echo waiting for pgsql; sleep 2; done;
        envVars:
          _include:
          - db-envs
        resources:
          requests:
            mcpu: 50
            memoryMb: 50
          limits:
            mcpu: null
            memoryMb: 50

apps-configmaps:
  service-env-configmap:
    _include: ["apps-configmaps-defaultConfigmap"]
    envVars:
      _include:
      - app-envs

apps-secrets:
  service-env-secret:
    _include: ["apps-configmaps-defaultSecret"]
    envVars:
      _include:
      - app-secret-envs

apps-stateless:
  super-redis:    
    _include: [ "apps-stateless-defaultApp" ]
    replicas:
      _default: 1
    containers:
      main:
        image:
          name: nginx
        ports: |
          - name: nginx
            containerPort: 80
        resources:
          requests:
            cpu:
              _default: 50m
              production: 100m
            memory:
              _default: 100Mi
          limits:
            memory:
              _default: 200Mi
    service:
      enabled: true
      ports: |
        - name: {{ $.CurrentApp.name }}
          port: 80
    verticalPodAutoscaler:
      enabled: false


apps-ingresses:
  test-shop:
    _include: ["apps-ingresses-defaultIngress"]
    infra_envs:
      _include:
      - app-envs
    ingressClassName: "nginx"
    annotations: |
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-body-size: "20m"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    host: '{{ $.Values.global.envUrl }}'
    paths: |
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ $.CurrentApp.name }}'
            port:
              number: 80
