name: Werf deploy

env:
  WERF_ENV: development
  WERF_NAMESPACE: default
  WERF_VALUES_ENV: .helm/values-envs.yaml
  WERF_SECRET_VALUES_ENV: .helm/secret-values.yaml

on:
  push:
    branches:
      - "actions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2
        
      - name: Run script for depoying to kubernetes
        run: |
          echo "${{ github.workspace }}"
          . $(werf ci-env github --as-file)
          werf cr login -u ${{ secrets.ECR_LOGIN }} -p ${{ secrets.ECR_PASSWORD }} 
          # alifbank/opencesear:tagname
          werf
        env:
            WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
            WERF_ENV: development
          
      - name: Run linux command on ubuntu
        run: |
          ls -alhi
          uname -ar
          pwd
          cat /etc/os-release | grep -i "^name"
      
        env:
          WERF_VALUES_ENV: .helm/values-envs.yaml
          WERF_RELEASE: "test-shop"
          WERF_SET_ENV_URL: "global.envUrl=opensearch.alif.pk"

          
