name: Service
  
on:
  push:
    branches:
      - "services"

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, jenkinsdevops]
    services:
      postgres1:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: db1
          POSTGRES_USER: user1
          POSTGRES_PASSWORD: password1

      postgres2:
        image: postgres:latest
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: db2
          POSTGRES_USER: user2
          POSTGRES_PASSWORD: password2

    steps:
    - uses: actions/checkout@v2
    - name: Wait for PostgreSQL to be ready
      run: |
        while ! nc -z localhost 5432; do
          sleep 1
        done
        while ! nc -z localhost 5433; do
          sleep 1
        done
    - name: Run Python script
      run: python3 connect_postgres.py
      env:
        POSTGRES1_HOST: localhost
        POSTGRES1_PORT: 5432
        POSTGRES1_DB: db1
        POSTGRES1_USER: user1
        POSTGRES1_PASSWORD: password1
        POSTGRES2_HOST: localhost
        POSTGRES2_PORT: 5433
        POSTGRES2_DB: db2
        POSTGRES2_USER: user2
        POSTGRES2_PASSWORD: password2
